[project]
name = "resume"
version = "0.1.0"
description = "Resume of Patrick St. Jean"
authors = [
    {name = "Patrick St. Jean",email = "stjeanp@pat-st-jean.com"}
]
readme = "README.md"
requires-python = "=3.13.5"
dependencies = [
    "jsonschema (>=4.26.0,<5.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "flask (>=3.1.3,<4.0.0)",
    "gunicorn (>=25.1.0,<26.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "cerberus (>=1.3.8,<2.0.0)"
]

[tool.poetry]
package-mode = false

[tool.poetry.requires-plugins]
poetry-plugin-shell = ">=1.0.1"
poethepoet = ">=0.45.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = ["gunicorn.conf.py", "app.py", "resume_app"]

[tool.pylint]
ignore-patterns = ["^\\.git", "^\\.poetry"]
recursive = true
source-roots = ["."]

[tool.black]
check = true
diff = true

[tool.pytest]
pythonpath = ["."]
addopts = ["--cov", "--cov-append", "--cov-report="]

[tool.poe.tasks.black]
help = "Check the code with black"
cmd = "black *.py resume_app tests"

[tool.poe.tasks.pylint]
help = "Check the code with pylint"
cmd = "pylint ."

[tool.poe.tasks.mypy]
help = "Check the code with mypy"
cmd = "mypy"

[dependency-groups]
dev = [
    "black (>=25.12.0,<27.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "mypy (>=1.19.1,<2.0.0)",
    "pip-audit (>=2.10.0,<3.0.0)",
    "pylint (>=4.0.5,<5.0.0)",
    "types-jsonschema (>=4.26.0.20260508,<5.0.0.0)"
]
