[project]
name = "resume"
version = "0.1.0"
description = "Resume of Patrick St. Jean"
authors = [
    {name = "Patrick St. Jean",email = "stjeanp@pat-st-jean.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "jsonschema (>=4.26.0,<5.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "flask (>=3.1.3,<4.0.0)",
    "gunicorn (>=26.0.0,<27.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "cerberus (>=1.3.8,<2.0.0)",
    "weasyprint (>=68.1,<70.0)"
]

[tool.poetry]
package-mode = false

[tool.poetry.requires-plugins]
poetry-plugin-shell = ">=1.0.1"
poethepoet = ">=0.45.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = ["gunicorn.conf.py", "app.py", "resume_app", "tests"]

[tool.pylint]
ignore-patterns = ["^\\.git", "^\\.poetry"]
recursive = true
source-roots = ["."]

[tool.black]
check = true
diff = true

[tool.pytest]
pythonpath = ["."]
addopts = ["--cov=tests", "--cov=resume_app", "--cov-append", "--cov-report="]

[tool.poe.tasks.black]
help = "Check the code with black"
cmd = "black *.py resume_app tests"

[tool.poe.tasks.pylint]
help = "Check the code with pylint"
cmd = "pylint ."

[tool.poe.tasks.mypy]
help = "Check the code with mypy"
cmd = "mypy"

[tool.poe.tasks.coverage_erase]
help = "Clear coverage data"
cmd = "coverage erase"

[tool.poe.tasks.coverage_report]
help = "Print the coverage report"
cmd = "coverage report -m --fail-under=100"

[tool.poe.tasks.unit_tests]
help = "Run the unit tests"
cmd = "pytest"

[tool.poe.tasks.pytest]
help = "Clear coverage data then run all unit tests and report the results" 
sequence = ["coverage_erase", "unit_tests", "coverage_report"]

[tool.poe.tasks.pip_audit]
help = "Scan the dependencies for vulnerabilities"
cmd = "pip-audit"

[tool.poe.tasks.code_quality]
help = "Run all code quality checks"
sequence = ["pylint", "mypy", "black", "pytest", "pip_audit"]

[dependency-groups]
dev = [
    "black (>=26.0.0,<27.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "mypy (>=2.0.0,<3.0.0)",
    "pip-audit (>=2.10.0,<3.0.0)",
    "pylint (>=4.0.5,<5.0.0)",
    "types-jsonschema (>=4.26.0.20260508,<5.0.0.0)"
]
